name:                cli-utils
version:             4.1.0
github:              "tbidne/cli-utils"
license:             BSD3
author:              "Thomas Bidne"
maintainer:          "tbidne@gmail.com"
copyright:           "2020 Thomas Bidne"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tbidne/cli-utils#readme>

dependencies:
- base >= 4.7 && < 5
- async
- clock
- containers
- monad-loops
- mtl
- parallel-io
- pretty-terminal
- process
- refined
- silently
- text
- time

ghc-options:
  - -O2
  - -Wall
  - -Wpartial-fields
  - -Wmissing-home-modules
  - -Widentities
  - -Wmissing-export-lists
  - -Wcompat
  - -Wredundant-constraints
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns

library:
  source-dirs: src

executables:
  cli-utils:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cli-utils

tests:
  spec:
    main: Spec.hs
    source-dirs: test/spec
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wno-orphans
    - -Wno-missing-export-lists
    dependencies:
    - cli-utils
    - hspec
    - hspec-core
    - QuickCheck
  inttest:
    main: Spec.hs
    source-dirs: test/inttest
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wno-orphans
    - -Wno-missing-export-lists
    dependencies:
    - cli-utils
    - hspec
    - hspec-core
    - QuickCheck
  functional:
    main: Spec.hs
    source-dirs: test/functional
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wno-orphans
    - -Wno-missing-export-lists
    dependencies:
    - cli-utils
    - hspec
    - hspec-core
    - silently
