name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup stack
        uses: mstksg/setup-stack@v1

      - name: Build
        run: stack build --ghc-options="-Werror"

      - name: Test
        run: stack test

