name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup stack
        uses: mstksg/setup-stack@v1

      - name: Build and test
        run: stack test --ghc-options="-Werror"

