name: docker push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: |
          docker rm -vf $(docker ps -a -q)
          docker rmi -f $(docker images -a -q)
          docker build . --file Dockerfile --tag tbidne/cli-utils:latest

      - name: Push to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: tbidne/cli-utils
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest"